### ISSUE TITLE
Library not working on windows due to fcntl import

### ISSUE THREAD

**Issue by keedziorek** [Jaymon/datatypes#51]
https://github.com/Jaymon/datatypes/blob/7e478e07712576c5d6fd9e6a98da7ac41e40a18e/datatypes/path.py#L26C3-L26C3

fcntl is not available for Windows

**Comment by Jaymon** [comment]
[This commit](https://github.com/Jaymon/datatypes/commit/ae2c14e59299679fd3c3c3b1f43a880359487794#diff-1392e539cd5a8814f072aae7ab1828764d1be661342828557e9b50f80b42d917) should fix it but I can't test
